{{- range $appName, $app := .Values.apps }}
{{- if $app.enabled | default true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ $app.replicas | default 1 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
        - image: "{{ $app.image.repository }}:{{ $app.image.tag | default "latest" }}"
          name: {{ $appName }}
      {{- with (include "app-chart.deployment.containerPorts" (dict "ports" $app.ports "appName" $appName)) }}{{ . | nindent 10 }}{{- end }}
      {{- with (include "app-chart.deployment.envFrom" (dict "envFrom" $app.envFrom)) }}{{ . | nindent 10 }}{{- end }}
      {{- with (include "app-chart.deployment.livenessProbe" (dict "livenessProbe" $app.livenessProbe "appName" $appName)) }}{{ . | nindent 10 }}{{- end }}
      {{- with (include "app-chart.deployment.volumeMounts" (dict "volumes" $app.volumes)) }}{{ . | nindent 10 }}{{- end }}
    {{- with (include "app-chart.deployment.volumes" (dict "volumes" $app.volumes)) }}{{ . | nindent 6 }}{{- end }}

{{- end }}
{{- end }}